version: "3"

services:
  backend:
    build: .
    container_name: backend
    ports:
      - "8000:8000"

  frontend:
    build: .
    container_name: frontend
    command: streamlit run ui.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - backend
